name: 'azure_devops'
version: 1.8.2+27
description: 'Azure DevOps unofficial mobile app'
homepage: 'homepage'
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.12'

dependencies:
  flutter: { sdk: flutter }
  google_fonts: ^4.0.4
  http: ^0.13.6
  shared_preferences: ^2.1.1
  pull_to_refresh_flutter3: ^2.0.1
  intl: ^0.18.1
  url_launcher: ^6.1.11
  share_plus: ^7.0.0
  sentry_flutter: ^7.6.1
  cached_network_image: ^3.2.3
  package_info_plus: ^3.1.2
  flutter_markdown: ^0.6.14
  flutter_html: ^3.0.0-alpha.6
  flutter_highlight: ^0.7.0
  in_app_review: ^2.0.6
  flutter_svg:
  purple_theme:
   git:
    url: https://github.com/PurpleSoftSrl/flutter_theme_manager
    ref: main

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_launcher_icons: ^0.13.1
  purple_lints:
    git:
      url: https://github.com/PurpleSoftSrl/flutter_lints
      ref: main


flutter:
  uses-material-design: true

  assets:
    - assets/app_icon/
    - assets/illustrations/
    - assets/fonts/
    - assets/logos/

  fonts:
    - family: DevOpsIcons
      fonts:
        - asset: assets/fonts/DevOpsIcons.ttf


flutter_icons:
  android: true
  ios: true 
  image_path: "assets/app_icon/app_icon_ios.png"
  adaptive_icon_background: "#201F1E"
  adaptive_icon_foreground: "assets/app_icon/app_icon_android.png"
  remove_alpha_ios: true